CheckerNetwork/spark-api

- bin/spark.js
- fly.toml
- package-lock.json
- package.json
> add sentry. closes #3

- index.js
> refactor `handler` / `errorHandler`

- README.md
- index.js
- migrations/005.do.wallet-address.sql
- migrations/005.undo.wallet-address.sql
- test/test.js
For https://github.com/filecoin-station/spark/issues/1
> Add submit wallet address

- README.md
- index.js
- migrations/011.do.attestation.sql
- migrations/011.undo.attestation.sql
- test/test.js
> Add store attestation. Closes #45

- index.js
- test/test.js
As discussed in [M2.1 Faster deployments of SPARK updates](https://www.notion.so/pl-strflt/SPARK-roadmap-to-LabWeek-23-5d41e603859a4e32908d3c818e3d4542?pvs=4#63f5f54be3614dcbac4ff4dad0a7c637)
> feat: reject outdated SPARK clients

- lib/round-tracker.js
Fix the bug where we were not able to handle SparkRound events.
> fix: forward RoundStarted event args

- README.md
Also improve formatting and layout in the section "Development".
> docs: describe Docker command for PostgreSQL

- bin/spark.js
- lib/migrate.js
Describe DB migrations and the HOST/PORT we are going to listen on
> feat: improve startup logging

- spark-publish/index.js
- spark-publish/test/test.js
Connect to:
- https://github.com/filecoin-station/spark/issues/13
> feat: add wallet address to published measurements

- bin/spark.js
Trying to get rid of the following error we are frequently observing:
Connection terminated unexpectedly
See also #78
> fix: tweak pg.Pool config

- spark-publish/index.js
- spark-publish/lib/telemetry.js
- spark-publish/package-lock.json
- spark-publish/package.json
Closes https://github.com/filecoin-station/spark-evaluate/issues/2
See also https://github.com/filecoin-station/spark-evaluate/pull/15
> Add telemetry

- index.js
- lib/round-tracker.js
- migrations/020.do.round-to-ie-mapping.sql
- test/round-tracker.test.js
- test/test.js
This reverts commit 79e7407e056e279ce74702b29c9283e5f319a056 (#101)
> Revert "feat: `GET /round/meridian/:address/:round` (#101)"

- Dockerfile
- bin/spark.js
- index.js
- test/test.js
We need to disallow access to `spark.fly.dev`, since it doesn't sit behind cloudflare
> add redirect to the right domain

- index.js
See https://github.com/filecoin-station/spark-api/pull/104#discussion_r1370132799
Links:
- https://github.com/filecoin-station/spark/issues/29
> feat: forward request-handler 5xx errors to Sentry

- .github/workflows/ci.yml
Prevent problems like #113 and #114 from reaching production.
> ci: verify Docker images can be built

- logshipper/fly.toml
See https://github.com/filecoin-station/spark-api/issues/108
Most of the configuration lives in Fly secrets.
> feat: setup log shipper service

- .github/workflows/dependabot-auto-approve-minor.yml
> ci: add auto approve minor `@sentry/*` updates

- spark-publish/bin/spark-publish.js
- spark-publish/index.js
- spark-publish/package-lock.json
- spark-publish/package.json
- spark-publish/test/test.js
Files are now published to the root entry of the CID (vs at `/measurements.json`), therefore this PR and the `spark-evaluate` PR need to be merged together.
Closes #141
> Integrate new web3.storage. Closes #141

- spark-publish/index.js
- spark-publish/test/test.js
Deploy after https://github.com/filecoin-station/spark-evaluate/pull/87
> switch to NDJSON

- index.js
- package-lock.json
- package.json
- test/test.js
Links:
- https://github.com/filecoin-station/roadmap/issues/52
> feat: reject measurements from spark versions <1.7.0

- lib/ie-contract.js
- spark-publish/bin/publish-batch.js
- spark-publish/ie-contract-config.js
Ref https://filecoinproject.slack.com/archives/C023K7D9GAX/p1703679868805479
Secrets have already been set in fly.io
> Add auth to glif requests

- spark-publish/index.js
- spark-publish/test/test.js
This is a follow-up for https://github.com/filecoin-station/spark-api/pull/184, see also https://github.com/filecoin-station/spark-api/pull/184#issuecomment-1876731586.
> feat: delete published measurements

- fly.toml
See https://github.com/filecoin-station/spark-stats/pull/2#discussion_r1452752585
> docs: remind us to sync Fly hard_limit and PG max

- spark-publish/bin/publish-batch.js
- spark-publish/bin/spark-publish.js
- spark-publish/package-lock.json
- spark-publish/package.json
Ethers v6 has better gas handling and is the more future ready version in general. Hopefully this brings down measure cost a little (not super important but helpful nevertheless)
> publish: update to ethers v6

- .github/workflows/ci.yml
For https://github.com/filecoin-station/roadmap/issues/69
> ci: add send slack message on `publish` deployment failure

- lib/round-tracker.js
- migrations/046.do.tasks-with-miner-id.sql
- test/round-tracker.test.js
Links:
- https://github.com/filecoin-station/roadmap/issues/65
> feat: add `miner_id` to per-round tasks

- index.js
- test/test.js
Links:
- https://github.com/filecoin-station/roadmap/issues/65
> fix: add `minerId` to per-round tasks

- index.js
- package-lock.json
- package.json
- test/test.js
When we added the address validation we hadn't realized that Station Core still submits f4 addresses as well. Fix in https://github.com/filecoin-station/core/pull/441, until the network all upgraded this patch is necessary
> fix accept f4 addresses

- spark-publish/bin/spark-publish.js
See https://github.com/filecoin-station/voyager-api/pull/36
> feat: log duration of single publishing iteration

- lib/round-tracker.js
- test/round-tracker.test.js
Fix the regression introduced by #264
> fix: Ethers v6 contract address getter

- spark-publish/index.js
> publish: Add retry `ie.addMeasurements()`. Closes #293

- .github/workflows/ci.yml
Extracted from https://github.com/filecoin-station/spark-api/pull/326
> ci: run CI for all pull requests

- publish/bin/publish-batch.js
This is commit fixes the regression introduced by #354.
> fix: recordTelemetry when publishing a batch

- migrations/054.do.index-retrievable-deals-client-id.sql
- migrations/055.do.index-retrievable-deals-miner-id.sql
Speed up the queries performed by API returning info about eligible deals.
Links:
- https://github.com/filecoin-station/spark-stats/pull/194
- https://github.com/filecoin-station/spark/issues/78
> perf: index retrievable deals by miner & by client

- migrations/054.do.index-retrievable-deals-client-id.sql
- migrations/055.do.index-retrievable-deals-miner-id.sql
This commit is trying to fix the failed deployment of 49670643.
Links:
- https://github.com/filecoin-station/spark-api/pull/390
- https://github.com/filecoin-station/spark/issues/78
> fix: create index only if not exists

- migrations/056.do.add-allocator-clients.sql
Links:
- https://github.com/filecoin-station/spark/issues/78
> feat: add allocator_clients table

- Dockerfile
- api/fly.toml
- publish/fly.toml
Related:
- https://github.com/filecoin-station/spark-api/issues/404
> chore: fix Docker lint errors

- migrations/060.do.cancel-stuck-transactions.sql
- package-lock.json
- publish/bin/publish-batch.js
- publish/bin/spark-publish.js
- publish/index.js
- publish/lib/cancel-stuck-transactions.js
- publish/package.json
- publish/test/pending-transactions-store.js
- publish/test/test.js
> publish: Add `cancel-pending-transactions`. Closes #425

- api/lib/round-tracker.js
- api/test/round-tracker.test.js
See also:
- https://github.com/filecoin-station/spark-evaluate/pull/382
> fix: maxTasksPerNode must be greater than zero

- api/lib/round-tracker.js
> round-tracker: fix set precision to bigint. #437

- api/test/round-tracker.test.js
Ref https://github.com/filecoin-station/spark-api/pull/441#pullrequestreview-2377427170
> Add passing test for upper task count limit

- api/test/round-tracker.test.js
Ref https://github.com/filecoin-station/spark-api/pull/437#discussion_r1806131718
> add passing test for scaling down measurement count

- .github/CODEOWNERS
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> add `CODEOWNERS`

- .github/workflows/dependabot-auto-approve-minor.yml
Based on https://github.com/CheckerNetwork/piece-indexer/pull/114
> ci: auto-approve Node.js minor/patch updates

- publish/index.js
- publish/test/test.js
Follow up for https://github.com/CheckerNetwork/spark-api/pull/692
https://github.com/CheckerNetwork/meridian-impact-evaluator/blob/14f630fb871f9b2e90bbcc8ad8b3e34c98d6ab2f/src/ImpactEvaluator.sol#L104
> publish: use ie#tick() instead of publishing an empty cid
