- bin/spark.js
See https://github.com/brianc/node-postgres/issues/1324#issuecomment-308778405
Fixes crashes like:
```
2023-07-25T08:22:40.841 app[17814d5b527638] cdg [info] Error: Connection terminated unexpectedly
2023-07-25T08:22:40.841 app[17814d5b527638] cdg [info] at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:132:73)
2023-07-25T08:22:40.841 app[17814d5b527638] cdg [info] at Object.onceWrapper (node:events:627:28)
2023-07-25T08:22:40.841 app[17814d5b527638] cdg [info] at Connection.emit (node:events:513:28)
2023-07-25T08:22:40.841 app[17814d5b527638] cdg [info] at Connection.emit (node:domain:489:12)
2023-07-25T08:22:40.841 app[17814d5b527638] cdg [info] at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:63:12)
2023-07-25T08:22:40.841 app[17814d5b527638] cdg [info] at …
```
> Fix idle pg connection crash

- test/test.js
Before my change, the mocha process would print test summary and then wait for around two seconds before exiting.
In this change, I am adding a call to `server.closeAllConnections()` to make sure there are no pending HTTP connections blocking the exit.
While changing the `after` hook, I also fixed it to `await` until the PG client is closed.
> test: remove delay before exit

- bin/spark.js
- lib/round-tracker.js
I am seeing all `POST /retrievals` request failing with the following
error:
```
error: null value in column "created_at_round" of relation "retrievals" violates not-null constraint
```
This commit tries to fix the problem by adding a forgotten `await`
statement to the code initialising the round tracker.
The problem was introduced by https://github.com/filecoin-station/spark-api/pull/61
> fix: wait for current round before starting

- index.js
- migrations/016.do.measurements.sql
- migrations/016.do.standalone-retrieval-results.sql
- spark-publish/index.js
- test/test.js
1. Decouple `retrieval_results` table from `retrieval` to allow us to submit results for retrieval tasks with no linked `retrieval` row.
2. Rename `retrieval_results` to `measurements` to align with MERidian vocabulary.
3. Update `setRetrievalResult` to support the new data schema. This allows existing SPARK checkers to keep reporting measurements.
4. Remove `GET /retrieval/:id` endpoint and replace it with a new endpoint `GET /measurements/:id`. This endpoint is used by integration tests in SPARK checker, we will need to update these tests after this PR lands.
5. Create a new endpoint for submitting retrieval results based on per-round tasks - `POST /measurements`.
I am envisioning the following workflow for the SPARK checker node:
1. Get the current round & the tasks via `GET …
> feat: decouple retrieval results from retrievals

- fly.toml
- Increase grace period to 10s, we are fetching FEVM state at startup
- Configure the healthcheck URL as `/rounds/current`. After my recent changes, the root URL `/` is returning 404, and thus failing the check.
> fix: healthcheck config

- fly.toml
This is a follow-up for https://github.com/filecoin-station/spark-api/pull/86 - we want to listen on all network interfaces when running in Fly.io
> fix: set HOST in Fly.toml

- migrations/017.do.index-measurements-by-time.sql
Many Grafana charts are filtering and grouping using this column, I hope the index will improve performance of those queries.
> perf: add index for `measurements.finished_at`

- spark-publish/index.js
- spark-publish/test/test.js
Some measurements contain wallet addresses that are not valid (cannot be converted to ETH `0x...` format). As a result, we are no longer publishing any measurements, which means the MERidian contract is no longer advancing the rounds.
This change reverts all address conversions. We should filter out invalid addresses in the evaluation service.
See also:
- #89
- https://github.com/filecoin-station/spark/issues/13
> fix: don't convert wallet address to ETH format

- fly.toml
Trying to fix the following problem found in logs:
> Instance 080e126b565608 reached hard limit of 25 concurrent
> connections. This usually indicates your app is not closing
> connections properly or is not closing them fast enough for
> the traffic levels it is handling. Scaling resources, number
> of instances or increasing your hard limit might help.
> fix: allow up to 250 concurrent spark-api connections

- index.js
- lib/round-tracker.js
- migrations/020.do.round-to-ie-mapping.sql
- test/round-tracker.test.js
- test/test.js
Introduce a new API for obtaining SPARK round details for the given Meridian contract address + IE round.
Links:
- https://github.com/filecoin-station/spark/issues/13
> feat: `GET /rounds/meridian/:address/:round`

- index.js
- lib/round-tracker.js
- migrations/020.do.first-spark-round-for-meridian.sql
- test/round-tracker.test.js
- test/test.js
Introduce a new API for obtaining SPARK round details for the given Meridian contract address + IE round.
This is a reworked version of #101 that is much lighter on DB storage & migration.
Links:
- https://github.com/filecoin-station/spark/issues/13
> feat: `GET /round/meridian/:address/:round`

- index.js
The new endpoint tells the caller what IP addresses we see, as coming from
the IP stack, Fly.io and CloudFare. This is useful to verify our understanding
of how all reverse proxies interact together.
Links:
- https://github.com/filecoin-station/spark-api/pull/104
- https://github.com/filecoin-station/spark/issues/29
- https://developers.cloudflare.com/fundamentals/reference/http-request-headers/
- https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/
> feat: add an API to inspect request's IP address

- index.js
- lib/inet-grouping.js
- migrations/021.do.inet-group-for-measurements.sql
- package-lock.json
- package.json
- test/inet-grouping.test.js
- test/test.js
Convert the IP address of the SPARK checker node submitting a measurement into an IPv4 /24 subnet (e.g. 127.0.0.0).
Recognize `Fly-Client-IP` and `CF-Connecting-IP` request headers to obtain the real client address as observed by Fly's/CloudFlare's load balancer.
Requests coming via IPv6 (or other transports that IP) get assigned a hard-coded group `ipv6`.
Links:
- https://github.com/filecoin-station/spark/issues/29
> feat: record "inet_group" in measurements

- Dockerfile
- spark-publish/Dockerfile
- https://github.com/filecoin-station/spark-api/pull/104 required global `crypto` object which is not available in Node.js 18
- Node.js 20 has recently entered LTS
> chore: upgrade Dockerfiles to Node.js 20

- Dockerfile
- spark-publish/Dockerfile
Remove dependency on Volta, use Node.js official Docker image instead.
Unify the content of spark-api and spark-publish Dockerfiles
so that we consistently use the same setup everywhere.
> fix: rework spark-api Dockerfile

- spark-publish/index.js
- spark-publish/test/test.js
Links:
- https://github.com/filecoin-station/spark/issues/29
> fix: add `inet_group` to published measurements

- index.js
- test/test.js
Change the response error code from 5xx to 4xx so that we don't report the error to Sentry.
> The HyperText Transfer Protocol (HTTP) 410 Gone client error response code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent.
Sentry event: https://protocol-labs-ip.sentry.io/issues/4570961976/events/d32bf8aaa99d4475b3de596e8a97317f/
> fix: send 4xx error for removed endpoints

- index.js
- migrations/025.do.add-car-too-large.sql
- spark-publish/index.js
- spark-publish/test/test.js
- test/test.js
- feat: record the measurement field `car_too_large`
- feat: return `carTooLarge` in measurement details
- feat: `car_too_large` in published measurements
Links:
- https://github.com/filecoin-station/spark/issues/16
- https://github.com/filecoin-station/spark/pull/28
> feat: new measurement field `car_too_large`

- test/test.js
So that we don't have to change the tests when we tweak the number of tasks chosen for each round.
This is a follow-up for 86c3299d6, bb878bfc8 and 0c307518d.
> test: use the constant TASKS_PER_ROUND

- migrations/027.do.measurements-finished-at-with-timezone.sql
Make the data type consistent with other columns storing date-time values.
Note: the migration will take a long time because we have ~12M measurements.
I will run it manually before landing this PR. I verified this particular
migration can be applied multiple times - subsequent runs are a quick no-op.
> db: add timezone to `measurements.finished_at`

- spark-publish/index.js
- spark-publish/test/test.js
Modify spark-publish to include another telemetry field: load factor.  I.e. what fraction of measurements waiting to be published we were able to process.
The load factor should be under 100% most time. If it only occasionally goes over 100% then the service should be able to eventually self-heal.  The trouble starts when we are consistently over 100% - the backlog of unpublished measurements is growing faster than we can process it.
> feat: report load of spark-publish

- spark-publish/index.js
We want to measure totalCount / maxMeasurements.
This is a follow-up for #137.
> fix: formula for spark-publish load

- spark-publish/index.js
Count all rows only after we collected the rows to publish.  spark-api adds more measurements in between our queries. If we query the total count first and rows to publish second, we would report total count smaller than the count of published rows.
See #138
> fix: count of unpublished measurements

- migrations/028.do.index_unpublished_tasks.sql
- migrations/029.do.index_retrieval_tasks_round_id.sql
I examined the slowest queries recorded by `pg_stats_statements` plugin:
1. Find up to N unpublished measurements
2. Count all unpublished measurements
3. Find tasks for the given round
This pull request adds indices to speed up these queries.
Links:
- https://github.com/filecoin-station/spark-api/issues/144
**perf: index unpublished measurements**
1939 ms -> 31 ms
Before:
```
explain analyze SELECT COUNT(*) FROM measurements WHERE published_as IS NULL;
QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------
Finalize Aggregate  (cost=615123.03..615123.04 rows=1 width=8) (actual time=1934.862..1937.937 rows=1 loops=1)
->  Gather  (cost=615122.81..615123.02 rows=2 width=8) (actual …
```
> perf: index frequent queries

- bin/spark.js
- index.js
- lib/round-tracker.js
- migrations/030.do.meridian-details-in-spark-rounds.sql
- test/round-tracker.test.js
- test/test.js
Rework the implementation of `GET /rounds/current` to redirect to a permalink `GET /rounds/meridian/{addr}/{round}`. This allows us to cache better the data queried from our database.
1. The redirection logic does not need the database; it builds the new location using in-memory data.
In the future, we can rework spark-checker to determine the current round locally by querying the on-chain state of the Meridian contract.
2. The response for the permalink for a given meridian round is immutable and, therefore, can be cached forever. If all works out as expected, we should see only one request per round, and the CDN cache will take care of the rest.
I have also improved the database schema to store the meridian contract address and round index in `spark_rounds` in order to enable fast …
> perf: better caching of current round details

- bin/spark.js
- index.js
Deployment of https://github.com/filecoin-station/spark-api/pull/147 is failing because at startup, we are updating `spark_rounds` table with `meridian_contract` and `meridian_round` before running the database schema migration.
This PR changes the initialisation order: db migrations first and everything else afterwards.
> fix: migrate db schema before current round init

- lib/round-tracker.js
I am observing different number of retrieval tasks returned in the response to the following request:
```
GET /rounds/meridian/0xaaef78eaf86dcf34f275288752e892424dda9341/410
```
I suspect this depends on which Cloudfare enpoint I hit. When I add `/?fresh=1` to the URL, I bypass the CDN and get a correct response with 400 tasks.
I think this is caused when Cloudfare hits our endpoint while we are still populating `retrieval_tasks` table for the recently started round.
In this pull request, I am wrapping that code in a new SQL transaction, to make the creation of new round and its tasks atomic.
Links:
- https://github.com/filecoin-station/spark-api/pull/147
- https://github.com/filecoin-station/spark-api/issues/144
> fix: wrap creation of new rounds in transaction

- migrations/031.do.index_meridian_rounds_lookup.sql
- migrations/032.do.index_spark_round_timestamps.sql
Add two more indices:
- `spark_rounds (created_at)`
- `meridian_contract_versions (contract_address)`
Links:
- https://github.com/filecoin-station/spark-api/issues/144
> perf: index meridian & spark round lookups

- index.js
- spark-publish/test/test.js
- test/test.js
Before this change, when the client sent `end_at: null`, we would convert that value to `Date(null)`, which is the Unix epoch.
After this change, we preserve null values as null.
Links:
- https://github.com/filecoin-station/spark/issues/43
> fix: preserve date values set to `null`

- spark-publish/bin/publish-batch.js
- spark-publish/bin/spark-publish.js
- spark-publish/index.js
- spark-publish/lib/telemetry.js
We have two CLIs now: Once that runs the loop, and one that performs one iteration of the loop.
This way we shouldn't have any long-running memory gc issues
> Move `publish()` to own CLI, for memory

- lib/round-tracker.js
We have currently more than 500k retrieval templates to pick from, and the network has ~20k nodes, so let's spread the load on SPs.
This is a follow-up for https://github.com/filecoin-station/fil-deal-ingester/pull/8
> feat: bump up tasks/round to 4000

- index.js
- lib/round-tracker.js
- migrations/034.do.round-max-tasks-per-node.sql
- test/round-tracker.test.js
- test/test.js
Add a new per-round configuration parameter allowing us to tweak how many retrieval requests are performed by each checker node.
The concept of "tasks per node" is described in [SPARK tasking v2](https://www.notion.so/pl-strflt/SPARK-tasking-v2-604e26d57f6b4892946525bcb3a77104?pvs=4#ded1cd98c2664a2289453d38e2715643).
Links:
- https://github.com/filecoin-station/roadmap/issues/52
> feat: maxTasksPerNode in round details

- spark-publish/bin/spark-publish.js
- spark-publish/ie-contract-config.js
Stick with one JSON-RPC provider until it fails. This has the advantage that on downtime we don't keep retrying the same provider every other request
> Implement new RPC_URL rotation strategy

- migrations/035.do.commitments.sql
- spark-publish/index.js
- spark-publish/test/test.js
As discussed in [Scaling SPARK PG DB beyond 500 GiB](https://www.notion.so/pl-strflt/Scaling-SPARK-PG-DB-beyond-500-GiB-4d9b6a81e1ac497691440e5a359e979c#047dbd9db86947438d2c5b7d97b3a025), we are considering how to change our database so that we can delete historical measurements while preserving access to this historical data via commitments published to web3.storage (or IPFS in general).
In this pull request, I am proposing a solution:
- Create a new table `commitments` to keep track of all CIDs plus the time of publishing
- When publishing a new commitment, add a new record to this table
- To query historical data in the given date-time interval, we can obtain the list of CIDs published within that interval from the new table, then fetch measurements in each CID via web3.storage HTTP …
> feat: keep track of committed CIDs

- bin/spark.js
Remove the extra line in `bin/spark.js` that was acquiring a new PG connection that was never returned back to the pool.
> fix: don't create dangling PG client connection

- fly.toml
Collocate the API service with our database.
After this PR is landed, we need to manually recreate Fly VM machines to move the service from IAD (Virginia/USA) to CDG (Paris, France).
> fix: set Fly primary region to CDG

- migrations/037.do.composite-commitment-key.sql
It is possible for two commitments to have the same CID (eg when the round was empty).
> fix composite commitment key

- index.js
- migrations/038.do.measurement-indexer-result-car-checksum.sql
- spark-publish/index.js
- spark-publish/test/test.js
- test/test.js
Modify spark-api and spark-publish to record two new measurement fields:
- `indexerResult`
- `carChecksum`
Links:
- https://github.com/filecoin-station/spark/issues/40
- https://github.com/filecoin-station/spark/issues/30
> feat: record `indexerResult` and `carChecksum`

- lib/round-tracker.js
- test/round-tracker.test.js
spark-publish is not able to keep up with the number of measurements we are receiving. Let's reduce the number of tasks to allow the system to self-heal and give us more time to figure out how to scale this up.
> fix: 4x less tasks per round

- index.js
- migrations/043.do.measurements-without-provider.sql
- test/test.js
We don't have the providerAddress & protocol fields for deals that are not advertised to IPNI.
This PR fixes a regression introduced by #209.
Links:
- https://www.notion.so/pl-strflt/Moving-IPNI-queries-to-Spark-checkers-c58175c0f1c841e6bb82ac44a1472a98
- https://github.com/filecoin-station/spark/issues/40
> fix: allow measurements with no provider

- migrations/044.do.drop-retrieval-templates.sql
We are using `retrievable_deals` for defining per-round tasks now.
Links:
- https://www.notion.so/pl-strflt/Moving-IPNI-queries-to-Spark-checkers-c58175c0f1c841e6bb82ac44a1472a98
- https://github.com/filecoin-station/spark/issues/40
> feat: drop table `retrieval_templates`

- index.js
Discovered in https://github.com/filecoin-station/voyager/pull/3#discussion_r1513136835
> fix `cloudf{l}are` typo

- index.js
- test/test.js
- refactor-rename `retrieval` to `measurement` in the test
- add a new assertion for `indexerResult`
- include `indexerResult` in the response body
> fix: return `indexerResult` in measurement details

- spark-publish/fly.toml
To ensure only one instance is running at a time
> publish: set deploy strategy to rolling

- index.js
- migrations/048.do.measurements-station-id.sql
- spark-publish/index.js
- test/test.js
DRAFT, DO NOT MERGE
Links:
filecoin-station/roadmap#96
> feat: Add station_id field to measurements storage and publishing

- .github/dependabot.yml
https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/
> chore: enable Dependabot for spark-publish

- Dockerfile
- spark-publish/Dockerfile
It would be great to find a way how to automate this.
- Can Dependabot upgrade base image version for us?
- Alternatively, can we specify only the major version and let Docker pick the latest minor/patch version available at the time of building the image?
> deps: upgrade Node.js in Dockerfile

- index.js
- lib/round-tracker.js
- migrations/049.do.round-start-epoch.sql
- test/round-tracker.test.js
- test/test.js
In order to map SPARK rounds to DRAND randomness values, we need to know the epoch (block number) when the SPARK round started.
This pull request modifies the round tracker to query the start epoch and store in the database, and the REST API to include this new field in the round details responses.
Links:
- https://github.com/filecoin-station/spark/issues/27
- https://www.notion.so/pl-strflt/SPARK-tasking-v2-604e26d57f6b4892946525bcb3a77104#8fe99341a9a447b98f198021d536cc05
> feat: add "startEpoch" to round details

- spark-publish/index.js
- spark-publish/package-lock.json
- spark-publish/package.json
When waiting for confirmation of the `ie.addMeasurements()` transaction, implement a timeout of 2 minutes and retry scheme timing out after 10 minutes in total.
The goal is to prevent spark-publish from hanging indefinitely when the RPC API or the blockchain are not able to provide any confirmations.
Based on `add_measurements_duration_ms` collected in InfluxDB, most transactions are confirmed within 100 seconds, which is within the 2 minute timeout. There are occassional outliers going up to 500 seconds, they will be handled by the retries. We cannot afford to wait for the confirmation too long, otherwise we will not commit measurements before the round ends.
> feat: timeout & retry while waiting for FEVM tx

- spark-publish/index.js
- **fix: don't retry tx wait on CALL_EXCEPTION errors**
- **fix: retry timeout for `tx.wait()`**
> fix: tweak retrying of `tx.wait()`

- lib/round-tracker.js
I am trying the make the RPC API call easier to fulfill and thus return in the current timeout of 2 minutes even when Glif is under heavy load.
> fix: search RoundStart events only ~2h in the past

- migrations/050.do.index-measurements-by-time.sql
Apply https://github.com/filecoin-station/voyager-api/pull/29 from voyager-api.
Our observability tooling needs to find the oldest measurement, which is expensive to do without an index.
> perf: bring back index `measurements.published_at`

- spark-publish/index.js
- spark-publish/package-lock.json
- spark-publish/package.json
I noticed that spark-publish got again stuck for more than an hour today, I had
to restart the machine to resume publishing.
```
2024-05-14T09:19:55Z app[6e82994bee5798] cdg [info]Invoking ie.addMeasurements()...
2024-05-14T09:19:58Z app[6e82994bee5798] cdg [info]Waiting for the transaction receipt: 0x62111d12b4a6b79abf05fd8a8b40dd7aefab51ead06f810988e1e1eebfdc86b7
2024-05-14T10:46:10Z app[6e82994bee5798] cdg [info] INFO Sending signal SIGINT to main child process w/ PID 306
```
In this pull request, I extracted the step "Call contract with CID" into
a standalone function and wrapped the function call in `pTimeout`.
> fix: timeout for the entire smart-contract call

- bin/spark.js
- index.js
- lib/round-tracker.js
- test/test.js
**feat: decouple round tracker from API routes**
Rework API handlers to get the current round from the database.
Benefits:
- This commit fixes the long-standing bug where the REST API returned different current round depending on which worker process received the request. This was caused by different timing when each worker process detected a new RoundStarted event.
- The new architecture allows us to further decouple the round tracker from the API handler. We can run it in background to not block process startup or even extract it into a standalone service.
Downsides:
- More database queries. Before my changes, the current round was available in memory. Now we need to read it from the database.  Affected endpoints:
- `POST /measurements`
- `GET /rounds/current`
Note: The next commit …
> feat: decouple round tracker from API routes

- bin/spark.js
- lib/round-tracker.js
- test/round-tracker.test.js
Refactor cancellation of the background task created by `startRoundTracker` to use injected AbortSignal instead of returning a `close()` function.
> refactor: use AbortSignal instead of `close()`

- lib/ie-contract.js
Lotus does not support filters when using JSON-RPC, see https://github.com/filecoin-project/lotus/issues/11589
This PR supersedes #304
> fix: use polling for reading on-chain events

- lib/ie-contract.js
The action `sendRpcPayload` includes `payload` property but the action `receiveRpcResult` includes `result` property instead.
> fix: ethers provider debugging

- lib/round-tracker.js
Move the function from inside `startRoundTracker` to the top level.
This is another baby step towards a round tracker that does not block service startup.
Links:
- https://github.com/filecoin-station/spark-api/issues/311
> refactor: extract `updateSparkRound` function

- lib/round-tracker.js
I found a way how to access the ContractEventPayload from the contract event listener function. By getting the block number from the event data, we don't have to make another RPC call to find the block number via potentially expensive & slow `eth_getLogs`.
Very loosely related to:
- https://github.com/filecoin-station/spark-api/issues/311
> feat: get blockNumber from Ethers.js event data

- test/db.test.js
I noticed that subsequent runs of this test failed because the test
was trying to insert the same CID again.
duplicate key value violates unique constraint "retrievable_deals_pkey"
This commit fixes the problem by modifying the test to remove dummy
deals created by previous runs.
> test: clean DB before testing retrievable_deals PK

- publish/index.js
- publish/lib/telemetry.js
- publish/test/platform-test-helpers.js
- publish/test/test-helpers.js
- publish/test/test.js
This commit partially ports https://github.com/filecoin-station/voyager-api/pull/22 to this repository:
- Introduce test-helpers and platform-test-helpers
- Rework the test file to use these new helpers
> test(publish): use mocked telemetry recorder

- publish/test/test-helpers.js
- test-helpers/platform-test-helpers.js
Move `platform-test-helpers.js` from `/publish/test` to `/test-helpers` to make then available in `api` tests too.
This is a follow-up for:
- #354
> refactor: shared platform-test-helpers

- common/telemetry.js
Move the configuration of the writer token from plain-text code to Fly.io secrets.
> feat: process.env.INFLUXDB_TOKEN

- api/index.js
- api/test/test.js
Let's force the network to upgrade to the recently release Spark checker version that implements HTTP retrievals directly using the Fetch API.
See https://github.com/filecoin-station/spark/releases/tag/v1.13.0
> feat: require spark version >=1.13.0

- api/index.js
- api/lib/round-tracker.js
- api/test/test.js
- migrations/053.do.tasks-with-clients.sql
For each task selected for retrieval tests, add a new field `clients` with a list of client IDs like `f01234` that are storing the same PieceCID/PayloadCID with the same miner.
Note that a single `(cid, miner_id)` pair can and does identify more than one storage deal.
Links:
- https://github.com/filecoin-station/spark/issues/79
> feat: add `clients` to each task in round details

- README.md
- api/index.js
- api/test/test.js
This pull request moves the implementation of REST API exposing deals eligible for testing from spark-stats to spark-api, as discussed in https://github.com/filecoin-station/spark-stats/pull/194#discussion_r1713500083
Links:
- https://github.com/filecoin-station/spark-stats/pull/194
- https://github.com/filecoin-station/spark-stats/pull/196
- https://github.com/filecoin-station/spark-api/pull/388
- https://github.com/filecoin-station/spark/issues/78
Example request:
```
GET /miner/f0814049/deals/eligible/summary
```
Example response:
```json
{
"minerId": "f0814049",
"dealCount": 10006,
"clients": [
{ "clientId": "f02516933", "dealCount": 6880 },
{ "clientId": "f02833886", "dealCount": 3126 }
]
}
```
Example request:
```
GET /clients/f0215074/deals/eligible/summary
```
Example response: …
> feat: API for deals tracked per miner/client/allocator

- api/index.js
- api/test/test.js
- migrations/057.do.nullable-measurement-start-at.sql
This is a follow-up for https://github.com/filecoin-station/spark/pull/92
> fix: accept measurements with `startAt: null`

- migrations/059.do.commitments-size-round.sql
- publish/index.js
- publish/test/test.js
From time to time, when troubleshooting issues or trying to backfill statistics we don't collect, I wish we stored more information about commitments in our database.
In this pull request, I am adding three new columns:
- `measurement_count`
- `meridian_address`
- `meridian_round`
Note: It would be more efficient storage-wise to map meridian address+round to spark round number (reference `spark_rounds.id`). However, in the current implementation, when a commitment is added to a new round, we may not have a row in `spark_rounds` created yet. Changing that is out of scope of this pull request.
Related discussions:
- https://space-meridian.slack.com/archives/C06RPCL6QGL/p1726662716781129
> feat: record row-count & round index of commitments

- common/ie-contract-config.js
I believe chainup is responsible for the CI errors:
> JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
> remove chainup (fix ci)

- api/lib/ie-contract.js
This makes us use `eth_getFilterChanges` which should now work. If it doesn't, this will let us give feedback.
See also https://github.com/filecoin-station/spark-evaluate/pull/399
> ie-contract: Disable JSON-RPC polling

- api/index.js
- api/lib/round-tracker.js
- api/test/db.test.js
- api/test/round-tracker.test.js
- api/test/test.js
Stop using the table `retrievable_deals`.
This is a follow-up for https://github.com/filecoin-station/spark-api/pull/485, which introduced `eligible_deals` table, and https://github.com/filecoin-station/fil-deal-ingester/pull/30, which modified fil-deal-ingester to populate this new table.
Links:
- https://github.com/filecoin-station/fil-deal-ingester/issues/29
> feat: sample retrieval tasks from `eligible_deals`

- migrations/064.do.drop-retrievable-deals.sql
This is a follow-up for #486 where we started using `eligible_deals` instead.
Close https://github.com/filecoin-station/fil-deal-ingester/issues/29
> feat: drop table `retrievable_deals`

- api/lib/round-tracker.js
- api/test/round-tracker.test.js
Ref https://github.com/filecoin-station/spark-api/issues/311#issuecomment-2599838687
> Exponentially look at more blocks to handle the case when we have an outage and the rounds are not advanced frequently enough, while keeping the happy path performant.
> Add exponential backoff to `getRoundStartEpoch()`. #311

- api/bin/spark.js
- api/index.js
- api/test/test.js
See https://github.com/space-meridian/roadmap/issues/218
Create a new API endpoint allowing trusted clients like deal-observer to add
more deals to the list of deals eligible for retrieval testing.
TODO:
> feat: POST /eligible-deals-batch

- .github/workflows/ci.yml
- Dockerfile
Partially Fixes https://github.com/CheckerNetwork/roadmap/issues/210
Updated the Node.js base image from node:20.12.2-slim to node:22.13.1-slim, an LTS version, as requested in issue #210 of the roadmap repository.
> Updated the base node image in Dockerfile

- api/lib/round-tracker.js
- api/test/round-tracker.test.js
Recently, we discovered that there is a lot of deals using the same payload CID `bafkqaaa`. There are more than 22k deals, but only between 27 miners and 9 clients. As a result, when one of such deals is picked for testing, the list of clients is very long and full of duplicates.
Example:
https://api.filspark.com/rounds/meridian/0x8460766edc62b525fc1fa4d628fc79229dc73031/25039
In this change, I am modifying the query sampling eligible deals to de-duplicate the list of clients in each task.
> fix: deduplicate list of clients in retrieval tasks

- api/index.js
- api/test/test.js
- migrations/065.do.head-status-code.sql
- publish/index.js
- publish/test/test-helpers.js
For CheckerNetwork/spark#104
Will accept and publish data from https://github.com/CheckerNetwork/spark/pull/109. Neither PR is blocking the other, they can be merged in any order.
Next: Integrate into spark-evaluate -> https://github.com/CheckerNetwork/spark-evaluate/pull/475
> Add test HEAD requests. CheckerNetwork/spark#104

- Dockerfile
Replace ARG NODE_VERSION with direct version in Dockerfile
> Auto-update Node.js version in Dockerfiles #243

- Dockerfile
Reverts CheckerNetwork/spark-api#531
> We shouldn't upgrade to odd major versions of Node.js - @juliangruber
> Revert "Bump node from 22.13.1-slim to 23.8.0-slim"

- api/bin/spark.js
- api/index.js
- api/lib/inet-grouping.js
- api/lib/network-info-logger.js
- api/lib/round-tracker.js
- api/test/network-info-logger.test.js
- api/test/round-tracker.test.js
- api/test/test.js
- package-lock.json
- package.json
- publish/bin/publish-batch.js
- publish/bin/spark-publish.js
- publish/index.js
- test-helpers/platform-test-helpers.js
- tsconfig.json
Adds typescript support and type checking. Fixes incorrect types and changes block number types to use `BigInt` instead of `number`.
- Add `typescript` package and type packages for `mocha`, `node` and `pg`
- Add typescript type checking as part of `test` command
- Fix incorrect types 
- Convert all block number types to `BigInt` from `number`
Related to https://github.com/CheckerNetwork/roadmap/issues/80
> Add typescript type checking

- api/index.js
- api/test/test.js
We have recently introduced a new requirement - when an HTTP retrieval succeeded, the checker is required to test HEAD retrieval request too.  The preprocessing step in spark-evaluate discards measurements missing `head_status_code`.
Because a large part of the network is running an older version of Spark Checker, measurements from these nodes are rejected as invalid.  See https://github.com/CheckerNetwork/spark-evaluate/pull/498.
This patch is moving the validation step earlier to the pipeline by changing the minimum required Spark Checker version to 1.17.0.
Checker nodes running an older version will start receiving a helpful "OUTDATED CLIENT" error response.
A screenshot from the Spark Internal Dashboard showing the correlation between outdated checker client and rejected measurements:
> feat: require Spark Checker version >=1.17.0

- api/bin/spark.js
- api/index.js
- api/test/test.js
This PR removes domain redirects. This is a prerequesite to enabling spark api as an internal service.
Blocking https://github.com/CheckerNetwork/spark-0k-checker/pull/5
> chore: Remove domain redirect

- api/bin/spark.js
- api/index.js
- api/test/test.js
As we have decided on not using private networking to communicate between permissioned `spark-0k` nodes and the `spark-api` domain redirect should not pose an issue anymore. 
Reverts CheckerNetwork/spark-api#647
Related to #652
> Revert "chore: Remove domain redirect"

- publish/index.js
- publish/test/test.js
After we changed the 0k checker node to run all task as quickly as possible (see https://github.com/CheckerNetwork/spark-0k-checker/pull/26), we are hitting a deadlock where no measurements are reported towards the end of the round, and as a result, the round is never advanced.
In this patch, I am changing the publisher to commit a CID for an empty file (`bafkqaaa`) when no measurements were recorded.
> fix: publish empty batches to avoid staled rounds
